<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 HoltWinters | Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel</title>
  <meta name="description" content="Proyecto Series de Tiempo" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 HoltWinters | Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Proyecto Series de Tiempo" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 HoltWinters | Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel" />
  
  <meta name="twitter:description" content="Proyecto Series de Tiempo" />
  

<meta name="author" content="David Cardenas, Aldair Blanco, Gustavo Ruiz" />


<meta name="date" content="2024-05-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="Estacionalidad.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ejercicio Series de Tiempo</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Proyecto</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Analisis de la BD</a></li>
<li class="chapter" data-level="3" data-path="Justificacion..html"><a href="Justificacion..html"><i class="fa fa-check"></i><b>3</b> Justificacion.</a></li>
<li class="chapter" data-level="4" data-path="iDescomposicion.html"><a href="iDescomposicion.html"><i class="fa fa-check"></i><b>4</b> Descomposicion</a></li>
<li class="chapter" data-level="5" data-path="PromedioMovil..html"><a href="PromedioMovil..html"><i class="fa fa-check"></i><b>5</b> Promedio Movil.</a>
<ul>
<li class="chapter" data-level="5.1" data-path="PromedioMovil..html"><a href="PromedioMovil..html#análisis-de-nuestro-dataframe."><i class="fa fa-check"></i><b>5.1</b> Análisis de nuestro DataFrame.</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="PromedioMovil..html"><a href="PromedioMovil..html#boxplot-nacidos-por-año."><i class="fa fa-check"></i><b>5.1.1</b> BoxPlot Nacidos por año.</a></li>
<li class="chapter" data-level="5.1.2" data-path="PromedioMovil..html"><a href="PromedioMovil..html#numero-de-nacidos-por-fecha."><i class="fa fa-check"></i><b>5.1.2</b> Numero de Nacidos por fecha.</a></li>
<li class="chapter" data-level="5.1.3" data-path="PromedioMovil..html"><a href="PromedioMovil..html#ejemplo-promedio-movil-simple-sma"><i class="fa fa-check"></i><b>5.1.3</b> Ejemplo: Promedio Movil Simple SMA:</a></li>
<li class="chapter" data-level="5.1.4" data-path="PromedioMovil..html"><a href="PromedioMovil..html#ejemplo-promedio-movil-exponencial-ema"><i class="fa fa-check"></i><b>5.1.4</b> Ejemplo: Promedio Movil Exponencial EMA:</a></li>
<li class="chapter" data-level="5.1.5" data-path="PromedioMovil..html"><a href="PromedioMovil..html#conclusiones"><i class="fa fa-check"></i><b>5.1.5</b> Conclusiones:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="Rezagos.html"><a href="Rezagos.html"><i class="fa fa-check"></i><b>6</b> Rezagos</a></li>
<li class="chapter" data-level="7" data-path="Estacionalidad.html"><a href="Estacionalidad.html"><i class="fa fa-check"></i><b>7</b> Estacionalidad</a>
<ul>
<li class="chapter" data-level="7.1" data-path="Estacionalidad.html"><a href="Estacionalidad.html#porcentaje-de-estacionalidad-por-mes-y-año-2021-2024"><i class="fa fa-check"></i><b>7.1</b> Porcentaje de Estacionalidad por Mes y Año (2021-2024)</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="HoltWinters.html"><a href="HoltWinters.html"><i class="fa fa-check"></i><b>8</b> HoltWinters</a>
<ul>
<li class="chapter" data-level="8.0.1" data-path="HoltWinters.html"><a href="HoltWinters.html#nuestros-datos."><i class="fa fa-check"></i><b>8.0.1</b> Nuestros datos.</a></li>
<li class="chapter" data-level="8.0.2" data-path="HoltWinters.html"><a href="HoltWinters.html#aplicando-holt-winters."><i class="fa fa-check"></i><b>8.0.2</b> Aplicando Holt-Winters.</a></li>
<li class="chapter" data-level="8.0.3" data-path="HoltWinters.html"><a href="HoltWinters.html#conclusiones-holt-winters."><i class="fa fa-check"></i><b>8.0.3</b> Conclusiones Holt-Winters.</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="HoltWinters" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> HoltWinters<a href="HoltWinters.html#HoltWinters" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<br>
<div style="text-align:justify;">
<p>El modelo Holt-Winters es una técnica de suavizamiento para análisis de series de tiempo que es especialmente útil cuando los datos exhiben tendencias y patrones estacionales. Este modelo es una extensión del método de suavizamiento exponencial de Holt, diseñado para capturar la estacionalidad además de la tendencia.</p>
<p>Suavizamiento</p>
<p>El suavizamiento significa hacer los datos más regulares o uniformes, eliminando las fluctuaciones aleatorias y destacando tendencias o patrones importantes. El modelo utiliza fórmulas para combinar de manera ponderada estos tres componentes, ajustando los pesos (llamados parámetros de suavizamiento) para que se adapten de la mejor manera a los datos históricos.</p>
<p>Predicción</p>
<p>Para hacer predicciones, el modelo usa los valores estimados de nivel, tendencia y estacionalidad, proyectándolos hacia adelante. Esto es útil para planificar y tomar decisiones basadas en lo que se espera que ocurra en el futuro, considerando patrones pasados.</p>
<div/>
<p><br></p>
<p>Recordemos nuevamente nuestros datos:</p>
<div id="nuestros-datos." class="section level3 hasAnchor" number="8.0.1">
<h3><span class="header-section-number">8.0.1</span> Nuestros datos.<a href="HoltWinters.html#nuestros-datos." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><img src="_main_files/figure-html/serie_temporal_2-1.png" width="672" /></p>
<p>Validamos si nuestros datos son estacionarios:</p>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  serie_temporal
## Dickey-Fuller = -3.3185, Lag order = 5, p-value = 0.07122
## alternative hypothesis: stationary</code></pre>
<div style="text-align:justify;">
Dado que el valor p es menor que un nivel de significancia común, como 0.05, hay evidencia suficiente para rechazar la hipótesis nula de que la serie temporal es no estacionaria. Por lo tanto, en este caso, podemos concluir que la serie temporal es estacionaria.
<div/>

<p><br></p>
<div style="text-align:justify;">
Ahora utilizaremos la funcion descompose para ver la descomposicion de nuestra serie de tiempo en tres observaciones fundamentales como son Trend, seasonal y random. (despues del grafico se explica cada una).
<div/>

<p><br></p>
<p><img src="_main_files/figure-html/PlotDescompose-1.png" width="672" />
<br></p>
<div style="text-align:justify;">
<p><strong>Tendencia (Trend):</strong> La tendencia describe la dirección general en la que los datos cambian con el tiempo. En el contexto del modelo Holt-Winters, esta tendencia se identifica y se incorpora para realizar pronósticos futuros. En nuestra serie temporal, observamos fluctuaciones notables en la tendencia a lo largo de los años. Por ejemplo, a principios de 2019, la tendencia muestra una marcada disminución, seguida de un repunte hacia mediados de 2020 y posteriormente, una nueva caída. Sin embargo, a partir de 2022, la tendencia muestra un claro aumento en el número de nacimientos vivos, lo que sugiere una tendencia alcista continua.</p>
<p><strong>Estacionalidad (Seasonal):</strong> En el método Holt-Winters, la estacionalidad representa los patrones recurrentes que se presentan en los datos a intervalos regulares. El modelo detecta y pronostica estas fluctuaciones estacionales para mejorar la precisión de las predicciones. En relación con nuestra serie temporal, la prueba de Dickey-Fuller arrojó un valor por debajo de 0.05, lo que sugiere que nuestra serie de tiempo es estacionaria. Este resultado refuerza la confiabilidad en el modelo al identificar y prever adecuadamente las variaciones estacionales en los datos.</p>
<strong>Componente aleatorio (Random):</strong> El componente aleatorio en Holt-Winters representa la variación no sistemática o aleatoria en los datos que no puede ser explicada por la tendencia o la estacionalidad. El modelo intenta capturar este componente para mejorar la precisión de los pronósticos, notamos un fuerte ruido en los datos para nuestros valores aleatorios.
<div/>
<p><br></p>
</div>
<div id="aplicando-holt-winters." class="section level3 hasAnchor" number="8.0.2">
<h3><span class="header-section-number">8.0.2</span> Aplicando Holt-Winters.<a href="HoltWinters.html#aplicando-holt-winters." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<br>
<div style="text-align:justify;">

<p>A tener en cuenta los parametros de suavizados del modelo Holt-Winters.</p>
<p><strong>alpha:</strong> Este parámetro controla el suavizado exponencial para la estimación de la componente de nivel (nivel base) en el modelo. Indica cuánto peso se le da a las observaciones pasadas para predecir el nivel actual. Un valor más cercano a 1 significa que se da más peso a las observaciones pasadas, lo que resulta en una adaptación más lenta a los cambios.</p>
<p><strong>beta:</strong> Este parámetro controla el suavizado exponencial para la estimación de la componente de tendencia en el modelo. Indica cuánto peso se le da a las observaciones pasadas para predecir la tendencia actual. Al igual que alpha, un valor más cercano a 1 significa que se da más peso a las observaciones pasadas.</p>
<p><strong>gamma:</strong> Este parámetro controla el suavizado exponencial para la estimación de la componente estacional en el modelo. Indica cuánto peso se le da a las observaciones pasadas para predecir la estacionalidad actual. Al igual que con alpha y beta, un valor más cercano a 1 significa que se da más peso a las observaciones pasadas.</p>
<p>Existen dos formas de aplicar el modelo Holt-Winters:</p>
<p><strong>1. Método Holt-Winters aditivo:</strong></p>
<ul>
<li>En el método aditivo, la estacionalidad se agrega a la serie temporal.</li>
<li>La tendencia y la estacionalidad se suman al nivel base para obtener los valores observados.</li>
<li>Es más adecuado cuando la magnitud de la estacionalidad no cambia en proporción al nivel de la serie temporal. En otras palabras, la estacionalidad no crece o disminuye con el nivel de los datos.</li>
</ul>
<p>ahora aplicaremos nuestro modelo Holt-winter additive a nuestra serie de tiempo en el siguiente segmento de codigo:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="HoltWinters.html#cb19-1" tabindex="-1"></a>HW_additive <span class="ot">&lt;-</span> <span class="fu">HoltWinters</span>(dfts3, <span class="at">seasonal =</span> <span class="st">&quot;additive&quot;</span>)</span>
<span id="cb19-2"><a href="HoltWinters.html#cb19-2" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">&quot;alpha &quot;</span>,HW_additive<span class="sc">$</span>alpha, <span class="st">&quot; beta&quot;</span>,HW_additive<span class="sc">$</span>beta,<span class="st">&quot; gamma&quot;</span>, HW_additive<span class="sc">$</span>gamma)</span></code></pre></div>
<pre><code>## [1] &quot;alpha  0.24610451750226  beta 0.00257109348712916  gamma 0.375739470223313&quot;</code></pre>
<p>En la salida observamos como aplicamos nuestro modelo y tambien podria observar el valor de cada uno de nuestros coeficientes, pero en este caso solo nos interesan nuestros parametros de suavisado, a continuación se explicaran:</p>
<p><strong>alpha:</strong> es de 0.24610451750226 nuestro modelo alpha tiene un valor bajo, esto quiere decir que no se le da un mayor peso a las observaciones pasadas.</p>
<p><strong>beta:</strong> 0.00257109348712916 este valor es muy bajo lo que quiere decir que el modelo casi que no tiene en cuenta la tendencia actual.</p>
<p><strong>gamma:</strong> 0.375739470223313 este valor esta mas cercano a 1 que los anteriores lo cual lo consideramos como valor moderado, el cual otorga peso a las observaciones pasadas y recientes en la estimación de la estacionalidad actual.</p>
<p>Veamos el comportamiento de nuestro modelo <strong>Holt-Winters aditivo</strong></p>
<p><img src="_main_files/figure-html/HW_additive_plot-1.png" width="672" /></p>
<p>En general, el modelo demuestra eficacia en la predicción de valores promedio. Sin embargo, muestra debilidad al enfrentarse a cambios abruptos en la tendencia. Específicamente, el modelo Holt-Winters aditivo no logra anticipar estos cambios. A pesar de ello, procederemos a realizar pronósticos para los próximos 24 meses utilizando este modelo.</p>
<p><br></p>
<p><img src="_main_files/figure-html/forecastHWA-1.png" width="672" /></p>
<p>Reafirmamos el anterior parrafo:
“En general, el modelo demuestra eficacia en la predicción de valores promedio. Sin embargo, muestra debilidad al enfrentarse a cambios abruptos en la tendencia. Específicamente, el modelo Holt-Winters aditivo no logra anticipar estos cambios.”
cuando intentamos pronosticar los proximos 24 meses, vemos como nuestro modelo se apega demasiado a nuestros valores promedios.
<br></p>
<p><strong>2. Método Holt-Winters multiplicativo:</strong></p>
<p><br>
<br></p>
<p>El Método Holt-Winters multiplicativo es un enfoque de suavización exponencial utilizado en análisis de series temporales para predecir valores futuros. Este método es una extensión del método de suavización exponencial simple, que toma en cuenta tendencias y estacionalidad en los datos. En lugar de tratar estas componentes como aditivas, como se hace en el Método Holt-Winters aditivo, el Método Holt-Winters multiplicativo las considera como multiplicativas. Esto significa que tanto la tendencia como la estacionalidad se aplican multiplicativamente a los niveles de la serie temporal en lugar de sumarse directamente</p>
<ul>
<li>En el método multiplicativo, la estacionalidad se multiplica por la serie temporal.</li>
<li>La tendencia y la estacionalidad se multiplican al nivel base para obtener los valores observados.</li>
<li>Es más apropiado cuando la magnitud de la estacionalidad varía en proporción al nivel de la serie temporal. En este caso, la estacionalidad aumenta o disminuye en relación con el nivel de los datos.</li>
</ul>
<p>ahora aplicaremos nuestro modelo Holt-winter multiplicativo a nuestra serie de tiempo en el siguiente segmento de codigo:</p>
<pre><code>## [1] &quot;alpha  0.026371845082938  beta 0.0619052437826439  gamma 0.323835874454532&quot;</code></pre>
<p><strong>alpha:</strong> es de 0.026371845082938 nuestro modelo alpha tiene un valor bajo, esto quiere decir que no se le da un mayor peso a las observaciones pasadas, es un poco mas alta que el modelo aditivo.</p>
<p><strong>beta:</strong> 0.0619052437826439 este valor es muy bajo lo que quiere decir que el modelo casi no tiene en cuenta la tendencia actual, pero es mucho mas alto que el modelo aditivo.</p>
<p><strong>gamma:</strong> 0.323835874454532 este valor esta mas cercano a 1 que los anteriores lo cual lo consideramos como valor moderado, el cual otorga peso a las observaciones pasadas y recientes en la estimación de la estacionalidad actual, este valor es el unico que esta por debo con respecto al modelo aditivo.</p>
<p>Veamos el comportamiento de nuestro modelo <strong>Holt-Winters multiplicativo</strong></p>
<p><img src="_main_files/figure-html/HW_multiplicative_plot-1.png" width="672" /></p>
<p>En general, el modelo Holt-Winters multiplicativo demuestra eficacia en la predicción de valores promedio. Sin embargo, muestra debilidad al enfrentarse a cambios abruptos en la tendencia, siendo menos capaz de anticipar estos cambios que su contraparte aditiva. Además, en muchos picos tiende a disminuir el número de nacidos vivos, lo que sugiere que es más conservador en sus predicciones que el modelo aditivo.</p>
<p>A pesar de ello, procederemos a realizar pronósticos para los próximos 24 meses utilizando este modelo.</p>
<p><br></p>
<p><img src="_main_files/figure-html/forecastHWM_2-1.png" width="672" /></p>
<p>Reafirmamos el anterior parrafo:
En general, el modelo Holt-Winters multiplicativo demuestra eficacia en la predicción de valores promedio. Sin embargo, muestra debilidad al enfrentarse a cambios abruptos en la tendencia, siendo menos capaz de anticipar estos cambios que su contraparte aditiva. Además, en muchos picos tiende a disminuir el número de nacidos vivos, lo que sugiere que es más conservador en sus predicciones que el modelo aditivo.
”
cuando intentamos pronosticar los proximos 24 meses, vemos como nuestro modelo se apega demasiado a nuestros valores promedios, al igual que el modelo Holt-Winters Aditivo.</p>
<p><br>
<br></p>
</div>
<div id="conclusiones-holt-winters." class="section level3 hasAnchor" number="8.0.3">
<h3><span class="header-section-number">8.0.3</span> Conclusiones Holt-Winters.<a href="HoltWinters.html#conclusiones-holt-winters." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cuando intentamos pronosticar los próximos 24 meses, observamos cómo nuestro modelo Holt-Winters multiplicativo se adhiere demasiado a los valores promedio, al igual que el modelo Holt-Winters aditivo.</p>
<p>En general, ambos modelos demuestran eficacia en la predicción de valores promedio. Sin embargo, muestran debilidad al enfrentarse a cambios abruptos en la tendencia. Específicamente, el modelo Holt-Winters multiplicativo tiende a ser más conservador en sus predicciones, mientras que el modelo aditivo puede subestimar o sobreestimar estos cambios.</p>
<p>Aunque ambos modelos son útiles para predecir valores promedio, es importante tener en cuenta sus limitaciones al enfrentarse a cambios repentinos en la tendencia. Es posible que se necesiten ajustes adicionales o considerar otros métodos de pronóstico para mejorar la capacidad de anticipar estos cambios, tambien podriamos hacer un hiper parametros tuning para tomar los mejores parametros para nuestros modelos.</p>
<div/>










</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="Estacionalidad.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07-HoltWinters.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
