<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Modelo estacional | Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel</title>
  <meta name="description" content="Proyecto Series de Tiempo" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Modelo estacional | Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Proyecto Series de Tiempo" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Modelo estacional | Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel" />
  
  <meta name="twitter:description" content="Proyecto Series de Tiempo" />
  

<meta name="author" content="David Cardenas, Aldair Blanco, Gustavo Ruiz" />


<meta name="date" content="2024-06-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="AjusteModeloLineal.html"/>
<link rel="next" href="modeloprophet.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ejercicio Series de Tiempo</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Proyecto</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#descripción-de-los-datos."><i class="fa fa-check"></i><b>1.1</b> Descripción de los datos.</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#vista-rapida-de-datos."><i class="fa fa-check"></i><b>1.2</b> Vista rapida de datos.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Justificacion..html"><a href="Justificacion..html"><i class="fa fa-check"></i><b>2</b> Justificacion.</a></li>
<li class="chapter" data-level="3" data-path="iDescomposicion.html"><a href="iDescomposicion.html"><i class="fa fa-check"></i><b>3</b> Descomposicion</a></li>
<li class="chapter" data-level="4" data-path="Rezagos.html"><a href="Rezagos.html"><i class="fa fa-check"></i><b>4</b> Rezagos</a></li>
<li class="chapter" data-level="5" data-path="Estacionalidad.html"><a href="Estacionalidad.html"><i class="fa fa-check"></i><b>5</b> Estacionalidad</a>
<ul>
<li class="chapter" data-level="5.1" data-path="Estacionalidad.html"><a href="Estacionalidad.html#porcentaje-de-estacionalidad-por-mes-y-año-2021-2024"><i class="fa fa-check"></i><b>5.1</b> Porcentaje de Estacionalidad por Mes y Año (2021-2024)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="PromedioMovil..html"><a href="PromedioMovil..html"><i class="fa fa-check"></i><b>6</b> Promedio Movil.</a>
<ul>
<li class="chapter" data-level="6.1" data-path="PromedioMovil..html"><a href="PromedioMovil..html#análisis-de-nuestro-dataframe."><i class="fa fa-check"></i><b>6.1</b> Análisis de nuestro DataFrame.</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="PromedioMovil..html"><a href="PromedioMovil..html#boxplot-nacidos-por-año."><i class="fa fa-check"></i><b>6.1.1</b> BoxPlot Nacidos por año.</a></li>
<li class="chapter" data-level="6.1.2" data-path="PromedioMovil..html"><a href="PromedioMovil..html#numero-de-nacidos-por-fecha."><i class="fa fa-check"></i><b>6.1.2</b> Numero de Nacidos por fecha.</a></li>
<li class="chapter" data-level="6.1.3" data-path="PromedioMovil..html"><a href="PromedioMovil..html#ejemplo-promedio-movil-simple-sma"><i class="fa fa-check"></i><b>6.1.3</b> Ejemplo: Promedio Movil Simple SMA:</a></li>
<li class="chapter" data-level="6.1.4" data-path="PromedioMovil..html"><a href="PromedioMovil..html#ejemplo-promedio-movil-exponencial-ema"><i class="fa fa-check"></i><b>6.1.4</b> Ejemplo: Promedio Movil Exponencial EMA:</a></li>
<li class="chapter" data-level="6.1.5" data-path="PromedioMovil..html"><a href="PromedioMovil..html#conclusiones"><i class="fa fa-check"></i><b>6.1.5</b> Conclusiones:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="HoltWinters.html"><a href="HoltWinters.html"><i class="fa fa-check"></i><b>7</b> HoltWinters</a>
<ul>
<li class="chapter" data-level="7.0.1" data-path="HoltWinters.html"><a href="HoltWinters.html#nuestros-datos."><i class="fa fa-check"></i><b>7.0.1</b> Nuestros datos.</a></li>
<li class="chapter" data-level="7.0.2" data-path="HoltWinters.html"><a href="HoltWinters.html#aplicando-holt-winters."><i class="fa fa-check"></i><b>7.0.2</b> Aplicando Holt-Winters.</a></li>
<li class="chapter" data-level="7.0.3" data-path="HoltWinters.html"><a href="HoltWinters.html#conclusiones-holt-winters."><i class="fa fa-check"></i><b>7.0.3</b> Conclusiones Holt-Winters.</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="AjusteModeloLineal.html"><a href="AjusteModeloLineal.html"><i class="fa fa-check"></i><b>8</b> AjusteModeloLineal</a>
<ul>
<li class="chapter" data-level="8.1" data-path="AjusteModeloLineal.html"><a href="AjusteModeloLineal.html#modelo-lineal"><i class="fa fa-check"></i><b>8.1</b> Modelo Lineal</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="AjusteModeloLineal.html"><a href="AjusteModeloLineal.html#resultados-del-modelo"><i class="fa fa-check"></i><b>8.1.1</b> Resultados del Modelo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="modelo-estacional.html"><a href="modelo-estacional.html"><i class="fa fa-check"></i><b>9</b> Modelo estacional</a></li>
<li class="chapter" data-level="10" data-path="modeloprophet.html"><a href="modeloprophet.html"><i class="fa fa-check"></i><b>10</b> ModeloProphet</a></li>
<li class="chapter" data-level="11" data-path="modeloredesneuronales.html"><a href="modeloredesneuronales.html"><i class="fa fa-check"></i><b>11</b> ModeloRedesNeuronales</a>
<ul>
<li class="chapter" data-level="11.1" data-path="modeloredesneuronales.html"><a href="modeloredesneuronales.html#modelo-de-redes-neuronales"><i class="fa fa-check"></i><b>11.1</b> Modelo de Redes Neuronales</a></li>
<li class="chapter" data-level="11.2" data-path="modeloredesneuronales.html"><a href="modeloredesneuronales.html#resultados"><i class="fa fa-check"></i><b>11.2</b> Resultados</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Analisis para Nacidos Vivos en el hospital Manuel Uribe Angel</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelo-estacional" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Modelo estacional<a href="modelo-estacional.html#modelo-estacional" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><strong>Modelo ARIMA</strong></p>
<p>ARIMA significa “Autoregressive Integrated Moving Average”, es un modelo estadístico ampliamente utilizado para analizar y predecir series temporales. Es especialmente útil para series que son estacionarias o que pueden ser transformadas en estacionarias mediante diferenciación. El modelo ARIMA combina tres componentes básicos: autorregresión (AR), diferenciación (I) y promedios móviles (MA).</p>
<p><strong>Componentes del modelo ARIMA</strong></p>
<p>AR (p) - Autorregresión: Un componente que usa la dependencia entre una observación y un número de observaciones retrasadas (lagged observations). El parámetro ‘p’ representa el número de términos autorregresivos. Por ejemplo, si p es 3, el valor predicho de la serie en un tiempo determinado sería una función de los valores en los tres periodos anteriores.</p>
<p>I (d) - Diferenciación: Este componente se utiliza para hacer la serie temporal estacionaria, es decir, para remover efectos como tendencias o ciclicidad. ‘d’ representa el número de diferenciaciones necesarias para alcanzar la estacionariedad. Si una serie temporal tiene una tendencia lineal, una diferenciación (d=1) debería ser suficiente para eliminar esa tendencia.</p>
<p>MA (q) - Promedio Móvil: Un modelo que usa la dependencia entre una observación y un residuo de un modelo de media móvil aplicado a observaciones retrasadas. El parámetro ‘q’ indica el número de términos del promedio móvil.</p>
<p><strong>Cómo funciona el modelo ARIMA</strong></p>
<p>El proceso de ajuste de un modelo ARIMA generalmente implica los siguientes pasos:</p>
<p>Identificación y Estimación: Determinar si la serie temporal necesita ser diferenciada para hacerla estacionaria (usualmente verificando la función de autocorrelación y la función de autocorrelación parcial). Luego, identificar los posibles valores para los parámetros p y q.</p>
<p>Estimación de parámetros: Usar técnicas como Máxima Verosimilitud o mínimos cuadrados para estimar los parámetros del modelo seleccionado.</p>
<p>Diagnóstico del modelo: Evaluar la calidad del modelo ajustado verificando si los residuos del modelo parecen ser “ruido blanco” (es decir, son estacionarios y no muestran patrones autocorrelativos).</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="modelo-estacional.html#cb19-1" tabindex="-1"></a><span class="co">#Cargar los datos y prepararlos</span></span>
<span id="cb19-2"><a href="modelo-estacional.html#cb19-2" tabindex="-1"></a></span>
<span id="cb19-3"><a href="modelo-estacional.html#cb19-3" tabindex="-1"></a><span class="fu">library</span>(dplyr, <span class="at">warn.conflicts =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-4"><a href="modelo-estacional.html#cb19-4" tabindex="-1"></a></span>
<span id="cb19-5"><a href="modelo-estacional.html#cb19-5" tabindex="-1"></a>DatosNacidos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;data/Nacidos_Vivos_en_Hospital_Manuel_Uribe_Angel_20240418.csv&quot;</span>)</span>
<span id="cb19-6"><a href="modelo-estacional.html#cb19-6" tabindex="-1"></a></span>
<span id="cb19-7"><a href="modelo-estacional.html#cb19-7" tabindex="-1"></a>DatosNacidos<span class="sc">$</span>FECHA <span class="ot">&lt;-</span> <span class="fu">substr</span>(DatosNacidos<span class="sc">$</span>FECHA,<span class="dv">1</span>,<span class="dv">10</span>)</span>
<span id="cb19-8"><a href="modelo-estacional.html#cb19-8" tabindex="-1"></a>DatosNacidos<span class="sc">$</span>FECHA <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(DatosNacidos<span class="sc">$</span>FECHA, <span class="at">format =</span> <span class="st">&quot;%m/%d/%Y&quot;</span>)</span>
<span id="cb19-9"><a href="modelo-estacional.html#cb19-9" tabindex="-1"></a></span>
<span id="cb19-10"><a href="modelo-estacional.html#cb19-10" tabindex="-1"></a>agrupnacidos <span class="ot">&lt;-</span> DatosNacidos <span class="sc">%&gt;%</span> </span>
<span id="cb19-11"><a href="modelo-estacional.html#cb19-11" tabindex="-1"></a>                   <span class="fu">group_by</span>(FECHA, MULTIPLICIDAD.EMBARAZO) <span class="sc">%&gt;%</span> </span>
<span id="cb19-12"><a href="modelo-estacional.html#cb19-12" tabindex="-1"></a>                   <span class="fu">summarize</span>(<span class="at">NumeroPartos =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb19-13"><a href="modelo-estacional.html#cb19-13" tabindex="-1"></a></span>
<span id="cb19-14"><a href="modelo-estacional.html#cb19-14" tabindex="-1"></a>agrupnacidos<span class="sc">$</span>NumeroNacidos <span class="ot">&lt;-</span> </span>
<span id="cb19-15"><a href="modelo-estacional.html#cb19-15" tabindex="-1"></a>  <span class="fu">ifelse</span>(agrupnacidos<span class="sc">$</span>MULTIPLICIDAD.EMBARAZO <span class="sc">==</span> <span class="st">&quot;DOBLE&quot;</span>,agrupnacidos<span class="sc">$</span>NumeroPartos<span class="sc">*</span><span class="dv">2</span>,agrupnacidos<span class="sc">$</span>NumeroPartos)</span>
<span id="cb19-16"><a href="modelo-estacional.html#cb19-16" tabindex="-1"></a></span>
<span id="cb19-17"><a href="modelo-estacional.html#cb19-17" tabindex="-1"></a>agrupnacidos_2 <span class="ot">&lt;-</span> agrupnacidos <span class="sc">%&gt;%</span> </span>
<span id="cb19-18"><a href="modelo-estacional.html#cb19-18" tabindex="-1"></a>                   <span class="fu">group_by</span>(FECHA) <span class="sc">%&gt;%</span> </span>
<span id="cb19-19"><a href="modelo-estacional.html#cb19-19" tabindex="-1"></a>                   <span class="fu">summarize</span>(<span class="at">NumeroNacidos=</span><span class="fu">sum</span>(NumeroNacidos), <span class="at">.groups =</span> <span class="st">&#39;drop&#39;</span>)</span>
<span id="cb19-20"><a href="modelo-estacional.html#cb19-20" tabindex="-1"></a></span>
<span id="cb19-21"><a href="modelo-estacional.html#cb19-21" tabindex="-1"></a></span>
<span id="cb19-22"><a href="modelo-estacional.html#cb19-22" tabindex="-1"></a><span class="fu">print</span>(agrupnacidos_2)</span></code></pre></div>
<pre><code>## # A tibble: 1,976 × 2
##    FECHA      NumeroNacidos
##    &lt;date&gt;             &lt;dbl&gt;
##  1 2018-01-01            10
##  2 2018-01-02            10
##  3 2018-01-03             6
##  4 2018-01-04             7
##  5 2018-01-05            14
##  6 2018-01-06            10
##  7 2018-01-07            11
##  8 2018-01-08             6
##  9 2018-01-09             7
## 10 2018-01-10            11
## # ℹ 1,966 more rows</code></pre>
<p>Visualizamos los datos</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="modelo-estacional.html#cb21-1" tabindex="-1"></a><span class="co"># Crear la serie de tiempo</span></span>
<span id="cb21-2"><a href="modelo-estacional.html#cb21-2" tabindex="-1"></a></span>
<span id="cb21-3"><a href="modelo-estacional.html#cb21-3" tabindex="-1"></a>dfts2 <span class="ot">&lt;-</span> <span class="fu">ts</span>(agrupnacidos_2<span class="sc">$</span>NumeroNacidos, <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2018</span>, <span class="dv">1</span>), <span class="at">end =</span> <span class="fu">c</span>(<span class="dv">2023</span>, <span class="dv">12</span>), <span class="at">frequency =</span> <span class="dv">12</span>)</span>
<span id="cb21-4"><a href="modelo-estacional.html#cb21-4" tabindex="-1"></a></span>
<span id="cb21-5"><a href="modelo-estacional.html#cb21-5" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb21-6"><a href="modelo-estacional.html#cb21-6" tabindex="-1"></a><span class="fu">plot</span>(dfts2, <span class="at">type =</span> <span class="st">&#39;l&#39;</span>, <span class="at">main =</span> <span class="st">&quot;Serie Temporal&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Valores&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Tiempo&quot;</span>)</span></code></pre></div>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/ts-1.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="modelo-estacional.html#cb22-1" tabindex="-1"></a><span class="fu">boxplot</span>(dfts2, <span class="at">horizontal =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">&quot;Boxplot de Serie Temporal&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Valores&quot;</span>)</span></code></pre></div>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/ts-2.png" width="672" /></p>
<p>Aplicamos el test de Dickey-Fuller Aumentado (ADF) para evaluar si una serie temporal es estacionaria o si contiene una raíz.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="modelo-estacional.html#cb23-1" tabindex="-1"></a><span class="co"># Cargar las bibliotecas necesarias</span></span>
<span id="cb23-2"><a href="modelo-estacional.html#cb23-2" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb23-3"><a href="modelo-estacional.html#cb23-3" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb23-4"><a href="modelo-estacional.html#cb23-4" tabindex="-1"></a><span class="fu">library</span>(aTSA)</span></code></pre></div>
<pre><code>## Warning: package &#39;aTSA&#39; was built under R version 4.2.3</code></pre>
<pre><code>## 
## Attaching package: &#39;aTSA&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tseries&#39;:
## 
##     adf.test, kpss.test, pp.test</code></pre>
<pre><code>## The following object is masked from &#39;package:forecast&#39;:
## 
##     forecast</code></pre>
<pre><code>## The following object is masked from &#39;package:graphics&#39;:
## 
##     identify</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="modelo-estacional.html#cb29-1" tabindex="-1"></a><span class="co"># Verificar estacionariedad</span></span>
<span id="cb29-2"><a href="modelo-estacional.html#cb29-2" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(dfts2)</span></code></pre></div>
<pre><code>## Augmented Dickey-Fuller Test 
## alternative: stationary 
##  
## Type 1: no drift no trend 
##      lag    ADF p.value
## [1,]   0 -1.798  0.0723
## [2,]   1 -1.288  0.2153
## [3,]   2 -0.726  0.4169
## [4,]   3 -0.516  0.4922
## Type 2: with drift no trend 
##      lag   ADF p.value
## [1,]   0 -6.82  0.0100
## [2,]   1 -5.57  0.0100
## [3,]   2 -3.42  0.0157
## [4,]   3 -2.32  0.2064
## Type 3: with drift and trend 
##      lag   ADF p.value
## [1,]   0 -7.26  0.0100
## [2,]   1 -6.12  0.0100
## [3,]   2 -3.94  0.0175
## [4,]   3 -2.80  0.2450
## ---- 
## Note: in fact, p.value = 0.01 means p.value &lt;= 0.01</code></pre>
<p>los resultados del test ADF sugieren que la serie temporal es estacionaria después de considerar estos componentes. Esto implica que cualquier tendencia o deriva en los datos originales puede explicarse por estos factores.</p>
<p>Este resultado indica que podría no necesitar diferenciar la serie para alcanzar la estacionariedad.</p>
<p>Con las graficas de autocorrelación (ACF) y la función de autocorrelación parcial (PACF) podemos explicar el comportamiento de los datos</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="modelo-estacional.html#cb31-1" tabindex="-1"></a><span class="co"># Graficar ACF y PACF</span></span>
<span id="cb31-2"><a href="modelo-estacional.html#cb31-2" tabindex="-1"></a></span>
<span id="cb31-3"><a href="modelo-estacional.html#cb31-3" tabindex="-1"></a><span class="fu">acf</span>(dfts2)</span></code></pre></div>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/ACF-PACF-1.png" width="672" /></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="modelo-estacional.html#cb32-1" tabindex="-1"></a><span class="fu">pacf</span>(dfts2)</span></code></pre></div>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/ACF-PACF-2.png" width="672" />
En la gráfica ACF:</p>
<p>Se observa un decrecimiento gradual en las barras de autocorrelación, empezando con un valor muy alto en el primer lag y luego disminuyendo lentamente. Esto sugiere la presencia de una dependencia que se extiende a varios lags.
Las barras que se extienden fuera del área azul (los límites de confianza) indican correlaciones significativas en esos lags.</p>
<p>En la gráfica PACF:</p>
<p>Hay dos lags donde las autocorrelaciones parciales son significativas (es decir, que se extienden más allá de los límites de confianza), específicamente en los primeros lags.
La mayoría de los valores vuelven a estar dentro del área de confianza.</p>
<p>Podemos empezar por un modelo ARIMA con bajos niveles de Autoregresión.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="modelo-estacional.html#cb33-1" tabindex="-1"></a><span class="co"># Asegúrate de cargar el paquete forecast</span></span>
<span id="cb33-2"><a href="modelo-estacional.html#cb33-2" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb33-3"><a href="modelo-estacional.html#cb33-3" tabindex="-1"></a></span>
<span id="cb33-4"><a href="modelo-estacional.html#cb33-4" tabindex="-1"></a><span class="co"># Ajusta un modelo ARIMA a la serie de tiempo dfts2</span></span>
<span id="cb33-5"><a href="modelo-estacional.html#cb33-5" tabindex="-1"></a>modelari2 <span class="ot">&lt;-</span> <span class="fu">auto.arima</span>(dfts2, <span class="at">stepwise =</span> <span class="cn">FALSE</span>, <span class="at">approximation =</span> <span class="cn">FALSE</span>, <span class="at">allowdrift =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-6"><a href="modelo-estacional.html#cb33-6" tabindex="-1"></a></span>
<span id="cb33-7"><a href="modelo-estacional.html#cb33-7" tabindex="-1"></a><span class="co"># Revisar el resumen del modelo, incluyendo los outliers</span></span>
<span id="cb33-8"><a href="modelo-estacional.html#cb33-8" tabindex="-1"></a><span class="fu">summary</span>(modelari2)</span></code></pre></div>
<pre><code>## Series: dfts2 
## ARIMA(2,1,1) 
## 
## Coefficients:
##           ar1      ar2      ma1
##       -0.1752  -0.3778  -0.6278
## s.e.   0.1481   0.1314   0.1313
## 
## sigma^2 = 8.069:  log likelihood = -173.98
## AIC=355.96   AICc=356.56   BIC=365.01
## 
## Training set error measures:
##                      ME     RMSE      MAE       MPE     MAPE      MASE
## Training set -0.1368662 2.760528 2.120021 -13.31024 30.00345 0.5888947
##                     ACF1
## Training set -0.03422207</code></pre>
<p>Apesar que las pruebas anteriores sugieren que la data es estacionaria, el modelo Auto.arima definio que debia hacerse una diferenciación para detectar estructuras en los datos que aún podrían beneficiarse, como pequeñas autocorrelaciones no detectadas en los tests de estacionariedad.</p>
<p>ACF1: -0.03422207, indica que hay poca autocorrelación en los residuos, lo cual es un buen indicativo de que el modelo está capturando adecuadamente la estructura de dependencia de los datos.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="modelo-estacional.html#cb35-1" tabindex="-1"></a><span class="co"># Extraer coeficientes del modelo</span></span>
<span id="cb35-2"><a href="modelo-estacional.html#cb35-2" tabindex="-1"></a>coeficientes <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelari2)</span>
<span id="cb35-3"><a href="modelo-estacional.html#cb35-3" tabindex="-1"></a></span>
<span id="cb35-4"><a href="modelo-estacional.html#cb35-4" tabindex="-1"></a><span class="co"># Identificar y extraer detalles de los outliers</span></span>
<span id="cb35-5"><a href="modelo-estacional.html#cb35-5" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> coeficientes[<span class="fu">grep</span>(<span class="st">&quot;AO|TC&quot;</span>, <span class="fu">names</span>(coeficientes))]</span>
<span id="cb35-6"><a href="modelo-estacional.html#cb35-6" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(outliers) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb35-7"><a href="modelo-estacional.html#cb35-7" tabindex="-1"></a>  <span class="fu">print</span>(outliers)</span>
<span id="cb35-8"><a href="modelo-estacional.html#cb35-8" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb35-9"><a href="modelo-estacional.html#cb35-9" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">&quot;No se encontraron outliers.</span><span class="sc">\n</span><span class="st">&quot;</span>)</span>
<span id="cb35-10"><a href="modelo-estacional.html#cb35-10" tabindex="-1"></a>}</span></code></pre></div>
<pre><code>## No se encontraron outliers.</code></pre>
<p>Aca se puede identificar que NO hay outliers estadísticamente significativos que necesitaran ser modelados. El modelo ARIMA(2,1,1) ha capturado adecuadamente la estructura de la serie temporal sin la necesidad de ajustar términos adicionales para outliers. Esto implica que la dinámica de la serie puede ser explicada suficientemente bien por las relaciones autorregresivas y de media móvil junto con la diferenciación que se incorporó.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="modelo-estacional.html#cb37-1" tabindex="-1"></a><span class="co"># Cargar las librerías necesarias</span></span>
<span id="cb37-2"><a href="modelo-estacional.html#cb37-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb37-3"><a href="modelo-estacional.html#cb37-3" tabindex="-1"></a></span>
<span id="cb37-4"><a href="modelo-estacional.html#cb37-4" tabindex="-1"></a><span class="co"># Preparar datos para graficar</span></span>
<span id="cb37-5"><a href="modelo-estacional.html#cb37-5" tabindex="-1"></a>ts_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Time =</span> <span class="fu">time</span>(dfts2), <span class="at">Data =</span> <span class="fu">as.numeric</span>(dfts2), <span class="at">Outlier =</span> <span class="fu">ifelse</span>(<span class="fu">time</span>(dfts2) <span class="sc">%in%</span> <span class="fu">names</span>(outliers), <span class="st">&quot;Yes&quot;</span>, <span class="st">&quot;No&quot;</span>))</span>
<span id="cb37-6"><a href="modelo-estacional.html#cb37-6" tabindex="-1"></a></span>
<span id="cb37-7"><a href="modelo-estacional.html#cb37-7" tabindex="-1"></a><span class="co"># Crear gráfico</span></span>
<span id="cb37-8"><a href="modelo-estacional.html#cb37-8" tabindex="-1"></a><span class="fu">ggplot</span>(ts_data, <span class="fu">aes</span>(<span class="at">x =</span> Time, <span class="at">y =</span> Data, <span class="at">color =</span> Outlier)) <span class="sc">+</span></span>
<span id="cb37-9"><a href="modelo-estacional.html#cb37-9" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb37-10"><a href="modelo-estacional.html#cb37-10" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> <span class="fu">subset</span>(ts_data, Outlier <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>), <span class="fu">aes</span>(<span class="at">x =</span> Time, <span class="at">y =</span> Data), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb37-11"><a href="modelo-estacional.html#cb37-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Time Series with Outliers&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Time&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Data&quot;</span>)</span></code></pre></div>
<pre><code>## Don&#39;t know how to automatically pick scale for
## object of type &lt;ts&gt;. Defaulting to continuous.</code></pre>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/grafica%20de%20outliers-1.png" width="672" /></p>
<p>Con esta grafica tratamos de visualizar los outliers, sin embargo, como lo vimos anteriormente, no se identificaron puntos específicos significativos en la serie temporal según el modelo ARIMA(2,1,1) ajustado.</p>
<p>Se hace un Check de los residuos para confirmar el diagnostico del modelo.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="modelo-estacional.html#cb39-1" tabindex="-1"></a><span class="co"># Diagnóstico de residuales</span></span>
<span id="cb39-2"><a href="modelo-estacional.html#cb39-2" tabindex="-1"></a><span class="fu">checkresiduals</span>(modelari2)</span></code></pre></div>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/Residuales-1.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(2,1,1)
## Q* = 7.6431, df = 11, p-value = 0.7449
## 
## Model df: 3.   Total lags used: 14</code></pre>
<p>Los residuos no muestran patrones autocorrelacionados significativos, lo cual es una buena señal en términos de ajuste del modelo.</p>
<p>El modelo ARIMA(2,1,1) ha hecho un buen trabajo modelando la serie temporal. Los residuos parecen ser mayormente no correlacionados y distribuidos de manera aleatoria alrededor del cero, y la prueba Ljung-Box confirma que no hay autocorrelación significativa en los residuos. Esto sugiere que el modelo es adecuado y que ha capturado la mayor parte de la información en los datos.</p>
<p>Un p-value alto (0.7449) sugiere que no hay evidencia suficiente para rechazar la hipótesis nula de independencia de los residuos, lo cual es consistente con los residuos comportándose como ruido blanco.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="modelo-estacional.html#cb41-1" tabindex="-1"></a><span class="co"># Predicción</span></span>
<span id="cb41-2"><a href="modelo-estacional.html#cb41-2" tabindex="-1"></a>future <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">forecast</span>(modelari2, <span class="at">h =</span> <span class="dv">12</span>)</span>
<span id="cb41-3"><a href="modelo-estacional.html#cb41-3" tabindex="-1"></a><span class="fu">plot</span>(future, <span class="at">main=</span><span class="st">&quot;Pronóstico con auto.arima&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Año&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;nacidos vivos&quot;</span>)</span>
<span id="cb41-4"><a href="modelo-estacional.html#cb41-4" tabindex="-1"></a><span class="fu">grid</span>()</span></code></pre></div>
<p><img src="https://raw.githubusercontent.com/davidc1228/BookdownST/main/_main_files/figure-html/prediccion-1.png" width="672" />
Las predicciones parecen seguir la tendencia y los patrones de los últimos datos observados. El modelo parece capturar bien las fluctuaciones de la serie y proyecta una continuación de esta dinámica en el corto plazo.</p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="AjusteModeloLineal.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modeloprophet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/09-modeloestacional.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
